version: '3'

services:

    client:
        image: node:8
        command: bash -c "cd /app && yarn install && yarn start"
        volumes:
            - ./web:/app
        ports: 
            - "4200:4200"
        expose:
            - "4200"